version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build Starting on `date`
      - npm run build
  post_build:
    commands:
      - echo Build completed

# Include pnly files required for your applications to run .
artifacts:
  files:
  - server.js
  - Procfile
  - build/**/*
  - public/**/*